steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git submodule init
        git submodule update
  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "docker/docker-compose.bird-mixit.yml", "pull"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["compose", "-f", "docker/docker-compose.bird-mixit.yml", "build"]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/bird-mixit:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/bird-mixit-gpu:latest"
options:
  logging: CLOUD_LOGGING_ONLY
