version: "3.8"
volumes:
  node_modules:
services:
  site:
    build:
      dockerfile: docker/Dockerfile.site
    restart: always
    volumes:
      - ./site:/site
      - node_modules:/app/node_modules
      - ${GCLOUD_CONFIG_PATH:-~/.config/gcloud}:/root/.config/gcloud
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
