version: "3.9"
services:
  app:
    build:
      dockerfile: docker/Dockerfile.app
      context: ..
      cache_from:
        - us-central1-docker.pkg.dev/birdclef-2023/birdclef-2023/app:latest
    image: us-central1-docker.pkg.dev/birdclef-2023/birdclef-2023/app:${TAG:-latest}
    working_dir: /app
    volumes:
      - ../:/app
