version: "3.9"
services:
  bird-mixit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bird-mixit
      cache_from:
        - us-central1-docker.pkg.dev/birdclef-2023/birdclef-2023/bird-mixit:latest
    image: us-central1-docker.pkg.dev/birdclef-2023/birdclef-2023/bird-mixit:${TAG:-latest}
    volumes: &volumes
      - ../scripts:/app/scripts
      - ../data:/mnt/data
  bird-mixit-gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bird-mixit-gpu
      cache_from:
        - us-central1-docker.pkg.dev/birdclef-2023/birdclef-2023/bird-mixit-gpu:latest
    image: us-central1-docker.pkg.dev/birdclef-2023/birdclef-2023/bird-mixit-gpu:${TAG:-latest}
    volumes: *volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
