FROM node:18

WORKDIR /site
COPY ./site/package* ./
RUN npm install

COPY ./site ./

ARG VITE_STATIC_HOST=https://storage.googleapis.com/birdclef-2023
ENV VITE_STATIC_HOST=${VITE_STATIC_HOST}
ENV PORT=${PORT:-8000}
RUN npm run build
CMD node build/index.js
