version: "3.9"
services:
  bird-mixit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bird-mixit
    image: us-central1-docker.pkg.dev/birdclef-eda-f22/birdclef-eda-f22/bird-mixit:latest
    volumes: &volumes
      - ../data/raw/sound_separation/bird_mixit_model_checkpoints:/app/checkpoints
      - ../scripts:/app/scripts
      - ../data:/mnt/data
  bird-mixit-gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bird-mixit-gpu
    image: us-central1-docker.pkg.dev/birdclef-eda-f22/birdclef-eda-f22/bird-mixit-gpu:latest
    volumes: *volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
