plugin: gcp_compute
auth_kind: application
projects:
  - birdclef-2023
regions:
  - us-central1
hostnames:
  - name
filters:
  - labels.app=dev
  - labels.version=ubuntu-2204
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
